import { mysqlSchema, varchar, decimal, index, datetime, date, text, double, bigint, int, float } from "drizzle-orm/mysql-core";

export const household = mysqlSchema("household");

export const dynamicMrCbIndihomeTable = (year: string, month: string) => {
    return household.table(`ih_mr_cb_indihome_mm_${year}${month}`, {
        bb_id: varchar('bb_id', { length: 20 }),
        telp_number: varchar('telp_number', { length: 20 }),
        status_migration: varchar('status_migration', { length: 30 }),
        status: decimal('status', { precision: 18, scale: 2 }),
        activation_date: varchar('activation_date', { length: 22 }),
        deactivation_date: varchar('deactivation_date', { length: 22 }),
        activatedDatetime: varchar('activated_datetime', { length: 25 }),
        sto: varchar('sto', { length: 12 }),
        area: varchar('area', { length: 10 }),
        region: varchar('region', { length: 20 }),
        city: varchar('city', { length: 30 }),
        branch: varchar('branch', { length: 30 }),
        cluster: varchar('cluster', { length: 30 }),
        bundle_transaction_id: varchar('bundle_transaction_id', { length: 45 }),
        bid: varchar({ length: 12 }),
        product_commercial_name: varchar('product_commercial_name', { length: 95 }),
        speed: varchar({ length: 100 }),
        flag_inet: varchar('flag_inet', { length: 3 }),
        flag_voice: varchar('flag_voice', { length: 3 }),
        flag_tv: varchar('flag_tv', { length: 3 }),
        flag_pda: varchar('flag_pda', { length: 3 }),
        order_pda: varchar('order_pda', { length: 30 }),
        usage_inet_octet: varchar('usage_inet_octet', { length: 22 }),
        usage_tv_sec: varchar('usage_tv_sec', { length: 22 }),
        usage_voice_sec: varchar('usage_voice_sec', { length: 22 }),
        total_billing: varchar('total_billing', { length: 22 }),
        kw_ih: varchar('kw_ih', { length: 4 }),
        per_ct0: varchar('per_ct0', { length: 12 }),
        ket_ct0: varchar('ket_ct0', { length: 11 }),
        flag_ct0: varchar('flag_ct0', { length: 3 }),
        months_arpu: varchar('3months_arpu', { length: 20 }),
        los: varchar('los', { length: 6 }),
        flag_cb_lm: varchar('flag_cb_lm', { length: 3 }),
        flag_cb_mtd: varchar('flag_cb_mtd', { length: 3 }),
        flag_sales_mtd: varchar('flag_sales_mtd', { length: 3 }),
        flag_churn_mtd: varchar('flag_churn_mtd', { length: 3 }),
        flag_cleansing_mtd: varchar('flag_cleansing_mtd', { length: 3 }),
        citem_inet: varchar('citem_inet', { length: 3 }),
        category_product: varchar('category_product', { length: 100 }),
        eventDate: varchar('event_date', { length: 12 }),
    }, t => [
        index('event_date').on(t.eventDate).using('btree'),
        index('city').on(t.city).using('btree'),
    ])
}

export const dynamicIhOrderingDetailOrderTable = (year: string, month: string) => {
    return household.table(`ih_ordering_detail_order_new_${year}${month}`, {
        sto_co: varchar('sto_co', { length: 50 }),
        kabupaten: varchar('kabupaten', { length: 50 }),
        cluster: varchar('cluster', { length: 50 }),
        branch: varchar('branch', { length: 50 }),
        wok: varchar('wok', { length: 255 }),
        region: varchar('region', { length: 30 }),
        area: varchar('area', { length: 30 }),
        order_id: varchar('order_id', { length: 255 }),
        package_type: varchar('package_type', { length: 255 }),
        order_type: varchar('order_type', { length: 255 }),
        order_mode: varchar('order_mode', { length: 255 }),
        order_initiator_id: varchar('order_initiator_id', { length: 255 }),
        order_initiator_id_type: varchar('order_initiator_id_type', { length: 255 }),
        process_state: varchar('process_state', { length: 255 }),
        provi_group: varchar('provi_group', { length: 255 }),
        provi_subgroup: varchar('provi_subgroup', { length: 255 }),
        funneling_group: varchar('funneling_group', { length: 255 }),
        funneling_subgroup: varchar('funneling_subgroup', { length: 255 }),
        provi_ts: datetime('provi_ts'),
        provi_duration: float('provi_duration'),
        name: varchar('name', { length: 255 }),
        no_handphone: varchar('no_handphone', { length: 255 }),
        address: varchar('address', { length: 255 }),
        segmentation: varchar('segmentation', { length: 255 }),
        order_ts: datetime('order_ts'),
        io_ts: datetime('io_ts'),
        re_ts: datetime('re_ts'),
        ps_ts: datetime('ps_ts'),
        completed_ts: datetime('completed_ts'),
        order_channel: varchar('order_channel', { length: 255 }),
        channel_name: varchar('channel_name', { length: 255 }),
        channel_group: varchar('channel_group', { length: 255 }),
        service_id: varchar('service_id', { length: 255 }),
        product_id_co: varchar('product_id_co', { length: 255 }),
        product_commercial_name: varchar('product_commercial_name', { length: 255 }),
        package_cat: varchar('package_cat', { length: 255 }),
        order_subtype: int('order_subtype'),
        order_status: varchar('order_status', { length: 255 }),
        order_status_desc: varchar('order_status_desc', { length: 255 }),
        payment_method: varchar('payment_method', { length: 255 }),
        order_amount: int('order_amount'),
        tgl_manja: varchar('tgl_manja', { length: 255 }),
        detail_manja: varchar('detail_manja', { length: 255 }),
        prev_state: varchar('prev_state', { length: 255 }),
        prev_state_ts: datetime('prev_state_ts'),
        longitude: varchar('longitude', { length: 255 }),
        latitude: varchar('latitude', { length: 255 }),
        appointment_id: varchar('appointment_id', { length: 255 }),
        appointment_start: datetime('appointment_start'),
        appointment_end: datetime('appointment_end'),
        reservation_id_odp: varchar('reservation_id_odp', { length: 255 }),
        c_wonum: varchar('c_wonum', { length: 255 }),
        c_actstart: varchar('c_actstart', { length: 255 }),
        c_actfinish: varchar('c_actfinish', { length: 255 }),
        c_errorcode: varchar('c_errorcode', { length: 255 }),
        c_suberrorcode: varchar('c_suberrorcode', { length: 255 }),
        c_engineermemo: varchar('c_engineermemo', { length: 255 }),
        c_urlevidence: varchar('c_urlevidence', { length: 255 }),
        c_amcrew: varchar('c_amcrew', { length: 255 }),
        c_chief_code: varchar('c_chief_code', { length: 255 }),
        c_chief_name: varchar('c_chief_name', { length: 255 }),
        last_update: datetime('last_update'),
        customer_account_id: varchar('customer_account_id', { length: 255 }),
        channel_transaction_id: varchar('channel_transaction_id', { length: 255 }),
        order_type_id: varchar('order_type_id', { length: 255 }),
        sf_name: varchar('sf_name', { length: 255 }),
        sf_contact_number: varchar('sf_contact_number', { length: 255 }),
        sf_email: varchar('sf_email', { length: 255 }),
        sf_company_name: varchar('sf_company_name', { length: 255 }),
        sf_branch_name: varchar('sf_branch_name', { length: 255 }),
        ro_ts: datetime('ro_ts'),
        pi_ts: datetime('pi_ts'),
        pc_ts: datetime('pc_ts'),
        odp_name: varchar('odp_name', { length: 255 }),
        fallout_source: varchar('fallout_source', { length: 255 }),
        fallout_category: varchar('fallout_category', { length: 255 }),
        fallout_subcategory: varchar('fallout_subcategory', { length: 255 }),
        fallout_reason: text('fallout_reason'),
        fiber_provisioning_type: varchar('fiber_provisioning_type', { length: 255 }),
        product_id_orbit: varchar('product_id_orbit', { length: 255 }),
        cancel_category: text('cancel_category'),
        cancel_reason: text('cancel_reason'),
        sla_duration: double('sla_duration'),
        sf_code: text('sf_code'),
        subchannel: text('subchannel'),
        referral_code: text('referral_code'),
        product_type: text('product_type'),
        deactivation_media: text('deactivation_media'),
        deactivation_reason: text('deactivation_reason'),
        list_sn_ont: text('list_sn_ont'),
        count_sn_ont: int('count_sn_ont'),
        list_sn_stb: text('list_sn_stb'),
        count_sn_stb: int('count_sn_stb'),
        list_sn_orbit: text('list_sn_orbit'),
        list_msisdn_orbit: text('list_msisdn_orbit'),
        count_sn_orbit: int('count_sn_orbit'),
        event_date: date('event_date'),
    }, t => [
        index('event_date').on(t.event_date).using('btree')
    ])
}

export const dynamicIhAvailOdpA4 = (year: string, month: string) => {
    return household.table(`ih_avail_odp_a4_${year}${month}`, {
        noss_id: varchar('noss_id', { length: 200 }),
        odp_index: varchar('odp_index', { length: 200 }),
        odp_name: varchar('odp_name', { length: 200 }),
        latitude: varchar('latitude', { length: 200 }),
        longitude: varchar('longitude', { length: 200 }),
        clusname: varchar('clusname', { length: 200 }),
        clustersatatus: varchar('clustersatatus', { length: 200 }),
        avai: varchar('avai', { length: 200 }),
        used: varchar('used', { length: 200 }),
        rsv: varchar('rsv', { length: 200 }),
        rsk: varchar('rsk', { length: 200 }),
        is_total: varchar('is_total', { length: 200 }),
        regional: varchar('regional', { length: 200 }),
        witel: varchar('witel', { length: 200 }),
        datel: varchar('datel', { length: 200 }),
        sto: varchar('sto', { length: 200 }),
        sto_desc: varchar('sto_desc', { length: 200 }),
        odp_info: varchar('odp_info', { length: 200 }),
        update_date: varchar('update_date', { length: 200 }),
        periode: varchar('periode', { length: 200 }),
        status: varchar('status', { length: 200 }),
        file_id: varchar('file_id', { length: 200 }),
        load_user: varchar('load_user', { length: 200 }),
        load_ts: varchar('load_ts', { length: 200 }),
        event_date: varchar('event_date', { length: 20 }),
    })
}

export const dynamicIhC3mr = (year: string, month: string) => {
    return household.table(`ih_c3mr_detail_dd_${year}${month}`, {
        nper: varchar('nper', { length: 10 }),
        bb_id: varchar('bb_id', { length: 30 }),
        telp_number: varchar('telp_number', { length: 20 }),
        account_num: varchar('account_num', { length: 20 }),
        name: varchar('name', { length: 50 }),
        address: varchar('address', { length: 70 }),
        email: varchar('email', { length: 100 }),
        no_hp: varchar('no_hp', { length: 20 }),
        area: varchar('area', { length: 20 }),
        region: varchar('region', { length: 20 }),
        branch: varchar('branch', { length: 20 }),
        cluster: varchar('cluster', { length: 30 }),
        city: varchar('city', { length: 30 }),
        sto: varchar('sto', { length: 5 }),
        los_category: varchar('los_category', { length: 15 }),
        usage: varchar('usage', { length: 20 }),
        product_type: varchar('product_type', { length: 20 }),
        customer_category: varchar('customer_category', { length: 20 }),
        customer_segment: varchar('customer_segment', { length: 20 }),
        exception: varchar('exception', { length: 100 }),
        outstanding: varchar('outstanding', { length: 50 }),
        service_type: varchar('service_type', { length: 50 }),
        billing_category: varchar('billing_category', { length: 15 }),
        speed_category: varchar('speed_category', { length: 10 }),
        bill_amount: varchar('bill_amount', { length: 50 }),
        paid_flag: varchar('paid_flag', { length: 5 }),
        payment_date: varchar('payment_date', { length: 20 }),
        payment_amount: varchar('payment_amount', { length: 50 }),
        cash_amount: varchar('cash_amount', { length: 50 }),
        claim_amount: varchar('claim_amount', { length: 50 }),
        event_date: varchar('event_date', { length: 20 }),
        load_date: varchar('load_date', { length: 20 }),
        source: varchar('source', { length: 20 }),
    })
}

export const fmcMconTable = household.table('fmc_mcon_final_dd', {
    notel: varchar({ length: 18 }),
    msisdnRecommendation: varchar('msisdn_recommendation', { length: 18 }),
    emailRecommendation: varchar('email_recommendation', { length: 100 }),
    alamatRecommendation: varchar('alamat_recommendation', { length: 255 }),
    latlong: varchar('latlong', { length: 30 }),
    msisdn_indri_verif: varchar('msisdn_indri_verif', { length: 18 }),
    msisdn_indri_not_verif: varchar('msisdn_indri_not_verif', { length: 18 }),
    msisdn_ncx: varchar('msisdn_ncx', { length: 18 }),
    msisdn_dbprofile: varchar('msisdn_dbprofile', { length: 18 }),
    msisdn_nossa_insera: varchar('msisdn_nossa_insera', { length: 18 }),
    msisdn_mytsel: varchar('msisdn_mytsel', { length: 18 }),
    msisdn_myih: varchar('msisdn_myih', { length: 18 }),
    msisdn_kpro: varchar('msisdn_kpro', { length: 18 }),
    msisdn_mydita: varchar('msisdn_mydita', { length: 18 }),
    msisdn_utonline: varchar('msisdn_utonline', { length: 18 }),
    email_indri_verif: varchar('email_indri_verif', { length: 60 }),
    email_indri_not_verif: varchar('email_indri_not_verif', { length: 50 }),
    email_ncx: varchar('email_ncx', { length: 50 }),
    email_dbprofile: varchar('email_dbprofile', { length: 50 }),
    email_nossa_insera: varchar('email_nossa_insera', { length: 50 }),
    email_myih: varchar('email_myih', { length: 50 }),
    email_kpro: varchar('email_kpro', { length: 50 }),
    email_mydita: varchar('email_mydita', { length: 50 }),
    email_utonline: varchar('email_utonline', { length: 50 }),
    alamat: varchar('alamat', { length: 150 }),
    alamat_kpro: varchar('alamat_kpro', { length: 150 }),
    alamat_mydita: varchar('alamat_mydita', { length: 150 }),
    alamat_utonline: varchar('alamat_utonline', { length: 150 }),
    longlitude: varchar('longlitude', { length: 35 }),
    latitude: varchar('latitude', { length: 35 }),
    longlitude_kpro: varchar('longlitude_kpro', { length: 35 }),
    latitude_kpro: varchar('latitude_kpro', { length: 35 }),
    longlitude_mydita: varchar('longlitude_mydita', { length: 35 }),
    latitude_mydita: varchar('latitude_mydita', { length: 35 }),
    longlitude_utonline: varchar('longlitude_utonline', { length: 35 }),
    latitude_utonline: varchar('latitude_utonline', { length: 40 }),
    eventDate: varchar('event_date', { length: 12 }),
}, t => [
    index('event_date').on(t.eventDate).using('btree')
])

export const ih_demand_mysiis = household.table('ih_demand_mysiis', {
    group: text('group'),
    area: text('area'),
    region: text('region'),
    branch: text('branch'),
    wok: text('wok'),
    regional: double('regional'),
    witel: text('witel'),
    id_desa: text('id_desa'),
    provinsi: text('provinsi'),
    kabupaten: text('kabupaten'),
    kecamatan: text('kecamatan'),
    desa: text('desa'),
    vendor: text('vendor'),
    id_polygon: bigint('id_polygon', { mode: 'number' }),
    nama_polygon: text('nama_polygon'),
    program: text('program'),
    assign: text('assign'),
    status_microde: text('status_microde'),
    status_permit: text('status_permit'),
    status_dashboard_ai: text('status_dashboard_ai'),
    status_new_bispro: text('status_new_bispro'),
    dokumen_bakp: text('dokumen_bakp'),
    dokumen_pending: double('dokumen_pending'),
    dokumen_drop: text('dokumen_drop'),
    submit: bigint('submit', { mode: 'number' }),
    valid_mitra: bigint('valid_mitra', { mode: 'number' }),
    valid: bigint('valid', { mode: 'number' }),
    invalid: bigint('invalid', { mode: 'number' }),
    total: bigint('total', { mode: 'number' }),
    target: bigint('target', { mode: 'number' }),
    progress: bigint('progress', { mode: 'number' }),
    high: bigint('high', { mode: 'number' }),
    medium: bigint('medium', { mode: 'number' }),
    low: bigint('low', { mode: 'number' }),
    not_priority: bigint('not_priority', { mode: 'number' }),
    last_surveyor: text('last_surveyor'),
    last_supervisor: text('last_supervisor'),
    last_date_survey: datetime('last_date_survey'),
    last_assigned: text('last_assigned'),
    approved_at: datetime('approved_at'),
    rejected_at: datetime('rejected_at'),
    assigned_at: datetime('assigned_at'),
    finished_survey_at: datetime('finished_survey_at'),
    pending_at: double('pending_at'),
    drop_at: datetime('drop_at'),
    done_at: datetime('done_at'),
    event_date: date('event_date'),
});

export const ih_occ_golive_ihld = household.table('ih_occ_golive_ihld', {
    odp_name: text('odp_name'),
    tanggal_go_live_uim: text('tanggal_go_live_uim'),
    tahun_go_live_uim: bigint('tahun_go_live_uim', { mode: 'number' }),
    tanggal_go_live_tomps: text('tanggal_go_live_tomps'),
    tahun_go_live_tomps: bigint('tahun_go_live_tomps', { mode: 'number' }),
    avai: bigint('avai', { mode: 'number' }),
    used: bigint('used', { mode: 'number' }),
    rsv: bigint('rsv', { mode: 'number' }),
    rsk: bigint('rsk', { mode: 'number' }),
    is_total: bigint('is_total', { mode: 'number' }),
    kategori: text('kategori'),
    occ_1: text('occ_1'),
    occ_2: text('occ_2'),
    latitude: double('latitude'),
    longitude: double('longitude'),
    nama_proyek: text('nama_proyek'),
    tipe_desain: text('tipe_desain'),
    ihld_lop_id: bigint('ihld_lop_id', { mode: 'number' }),
    jenis_program: text('jenis_program'),
    batch_program: text('batch_program'),
    tahun_program: bigint('tahun_program', { mode: 'number' }),
    regional: text('regional'),
    witel: text('witel'),
    datel: text('datel'),
    sto: text('sto'),
    wok: text('wok'),
    telkomsel_area: text('telkomsel_area'),
    telkomsel_regional: text('telkomsel_regional'),
    telkomsel_branch: text('telkomsel_branch'),
    telkomsel_cluster: text('telkomsel_cluster'),
    dibuat: text('dibuat'),
    diperbarui_pada: text('diperbarui_pada'),
    event_date: date('event_date'),
})

export const ih_information_odp = household.table('ih_information_odp', {
    service_name: varchar('service_name', { length: 100 }),
    service_number: varchar('service_number', { length: 25 }),
    package_name: varchar('package_name', { length: 50 }),
    download_speed: varchar('download_speed', { length: 50 }),
    odp_name: varchar('odp_name', { length: 100 }),
    event_date: varchar('event_date', { length: 25 }),
    rnum_b: int('rnum_b'),
})